# Auto-label PRs based on changed file paths
rfc:
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/**
meta:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
docs:
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/media/**
"area: platform":
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/platform/**
"area: backend":
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/backend/**
"area: mobile":
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/mobile/**

"area: data-analytics":
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/data-analytics/**

"area: general":
  - changed-files:
      - any-glob-to-any-file:
          - rfcs/general/**


